import { typeEntity, recordLabel } from './history.js';
import { filterLabels, normalizeFilters } from './filters.js';

const WIDTH=1080,HEIGHT=1350;
const pokemonImage=id=>`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${id}.png`;
function compactEntity(item){return{k:item.kind,n:item.name,i:item.id||0,t:item.type?.name||''}}
function encode(value){return btoa(unescape(encodeURIComponent(JSON.stringify(value)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function decode(value){return JSON.parse(decodeURIComponent(escape(atob(value.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-value.length%4)%4)))))}
export function createShareUrl(game,state){const data={v:2,g:game,c:state.correct,i:state.incorrect,f:normalizeFilters(state.filters),h:(state.history||[]).map(r=>({p:r.phase,c:r.correct,s:r.selected?.map(compactEntity)||[],e:r.expected?.map(compactEntity)||[],u:compactEntity(r.subject)}))};return `${location.origin}${location.pathname}#/share/${encode(data)}`}
export function decodeShareUrl(payload){const data=decode(payload),entity=item=>{if(item.k==='pokemon')return{...item,id:item.i||0,kind:'pokemon',label:item.n.split('-').map(x=>x[0].toUpperCase()+x.slice(1)).join(' '),imageUrl:item.i?pokemonImage(item.i):null};if(item.k==='move')return{...item,kind:'move',label:item.n.split('-').map(x=>x[0].toUpperCase()+x.slice(1)).join(' '),type:item.t?typeEntity(item.t):null,imageUrl:null};if(item.k==='none')return{kind:'none',name:'none',label:'Nenhum',imageUrl:null};return typeEntity(item.n)};return{game:data.g,correct:data.c,incorrect:data.i,score:0,filters:normalizeFilters(data.f),history:(data.h||[]).map(r=>({phase:r.p,correct:r.c,subject:entity(r.u),selected:r.s.map(entity),expected:r.e.map(entity)}))}}
function loadImage(url){return new Promise(resolve=>{if(!url)return resolve(null);const image=new Image();image.crossOrigin='anonymous';image.onload=()=>resolve(image);image.onerror=()=>resolve(null);image.src=url})}
function fitText(context,text,maxWidth){let value=text;while(value.length>3&&context.measureText(value+'...').width>maxWidth)value=value.slice(0,-1);return value===text?value:value+'...'}
function drawItem(context,record,index,images){const y=610+index*70,good=record.correct,item=record.subject;context.fillStyle=good?'#123b30':'#4a202b';context.beginPath();context.roundRect(60,y-42,960,58,14);context.fill();context.strokeStyle=good?'#34d399':'#ef3e4a';context.lineWidth=3;context.stroke();const image=images.get(item.imageUrl)||images.get(item.type?.imageUrl);if(image)context.drawImage(image,78,y-31,42,42);else{context.fillStyle='#b8c3d3';context.font='700 25px system-ui';context.fillText(item.kind==='type'?'◈':'✦',91,y-2)}context.fillStyle='#b8c3d3';context.font='700 22px system-ui';context.fillText(`#${record.phase}`,145,y-7);context.fillStyle='#fff';context.font='700 25px system-ui';context.fillText(fitText(context,recordLabel(item),300),215,y-7);context.fillStyle='#b8c3d3';context.font='500 19px system-ui';const selected=record.selected?.map(recordLabel).join(', ')||'—';context.fillText(fitText(context,`Você: ${selected}`,440),525,y-7);context.fillStyle=good?'#34d399':'#ff8992';context.font='800 30px system-ui';context.fillText(good?'✓':'×',965,y-5)}

export async function createShareCard(game,state){const history=state.history||[],urls=[...new Set(history.flatMap(record=>[record.subject?.imageUrl,record.subject?.type?.imageUrl].filter(Boolean)))],loaded=await Promise.all(urls.map(async url=>[url,await loadImage(url)])),images=new Map(loaded);const canvas=document.createElement('canvas');canvas.width=WIDTH;canvas.height=HEIGHT;const context=canvas.getContext('2d'),gradient=context.createLinearGradient(0,0,WIDTH,HEIGHT);gradient.addColorStop(0,'#172b52');gradient.addColorStop(1,'#070b12');context.fillStyle=gradient;context.fillRect(0,0,WIDTH,HEIGHT);context.fillStyle='#ef3e4a';context.beginPath();context.arc(920,150,250,0,Math.PI*2);context.fill();context.fillStyle='#5b8def';context.beginPath();context.arc(110,1190,170,0,Math.PI*2);context.fill();context.fillStyle='#f8fafc';context.font='800 48px system-ui, sans-serif';context.fillText('PokeAcademy',80,120);context.fillStyle='#82aaff';context.font='700 34px system-ui, sans-serif';context.fillText(game,80,205);context.fillStyle='#fff';context.font='800 82px system-ui, sans-serif';context.fillText(String(state.correct),80,380);context.fillText(String(state.incorrect),570,380);context.fillStyle='#b8c3d3';context.font='600 28px system-ui, sans-serif';context.fillText('ACERTOS',84,425);context.fillText('ERROS',574,425);context.fillStyle='#b8c3d3';context.font='600 27px system-ui, sans-serif';context.fillText(`${state.correct+state.incorrect} fases concluídas`,80,505);context.fillStyle='#82aaff';context.font='600 22px system-ui, sans-serif';context.fillText(fitText(context,filterLabels(state.filters).join(' · '),900),80,545);context.fillStyle='#f8fafc';context.font='700 28px system-ui, sans-serif';context.fillText('ÚLTIMAS RESPOSTAS',60,585);history.forEach((record,index)=>drawItem(context,record,index,images));const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('Não foi possível gerar o card.');return{blob,file:new File([blob],'pokeacademy-resultado.png',{type:'image/png'}),preview:canvas.toDataURL('image/png'),shareUrl:createShareUrl(game,state)}}
function downloadCard(blob){const url=URL.createObjectURL(blob),link=document.createElement('a');link.download='pokeacademy-resultado.png';link.href=url;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export async function shareResult(cardPromise,feedback){try{const{file,blob,shareUrl}=await cardPromise;if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file]});return}feedback.innerHTML=`<div class="qr-share"><strong>Continue pelo celular</strong><span>Escaneie o QR Code para compartilhar o card.</span><img src="https://api.qrserver.com/v1/create-qr-code/?size=260x260&data=${encodeURIComponent(shareUrl)}" alt="QR Code do resultado"><button class="download-card ghost">Baixar imagem neste PC</button></div>`;feedback.querySelector('.download-card').onclick=()=>downloadCard(blob)}catch(error){if(error.name!=='AbortError')feedback.textContent='Não foi possível compartilhar agora. Tente novamente.'}}
